name: Up Trend EGX Market Scan

on:
  schedule:
    - cron: '0 16 * * 1-5' # تشغيل تلقائي من الاثنين للجمعة الساعة 4 مساءً UTC
  workflow_dispatch: # إمكانية التشغيل اليدوي

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Install TA-Lib C-library
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ta-lib
          pip install yfinance pandas numpy scipy openpyxl tqdm requests

      - name: Run Chart Patterns
        run: python main.py

      - name: Upload Excel Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: EGX-Backtest-Results
          path: EGX_Triple_Bottom_Bulkowski_Results.xlsx
